apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: cohesity-demo
spec:
  type: NodePort
  ports:
  - name: "app-service"
    port: 8080
    targetPort: 80
    nodePort: 31000
  selector:
    app: app
  
