apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-init-role
  namespace: cohesity-demo
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
