apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-init-rolebinding
  namespace: cohesity-demo
subjects:
  - kind: ServiceAccount
    name: db-init-sa
    namespace: cohesity-demo
roleRef:
  kind: Role
  name: db-init-role
  apiGroup: rbac.authorization.k8s.io
