apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-config
  namespace: cohesity-demo
  labels:
    app: db
data:
  init.sql: |
    CREATE TABLE colors (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        color VARCHAR(255) NOT NULL
    );
