apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: cohesity-demo
  labels:
    app: db
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    app: db
