apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: cohesity-demo
  labels:
    app: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: POSTGRES_LISTEN_ADDRESSES
          value: "*"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres  # Ensures only this sub-directory is used inside PVC
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: block-storage-pvc  # Using your block storage PVC
